-- 프로그래머스
-- SQL 고득점 Kit : SUM, MAX, MIN
-- 중복 제거하기

-- ORACLE
-- DISTINCT 중복 제거
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL

-- MySQL
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL