-- LV1
-- String, Date
-- 자동차 대여 기록에서 장기/단기 대여 구분하기

-- MYSQL
SELECT
    -- SUBSTR(START_DATE, 1, 7)
    -- TO_CHAR(START_DATE, 'YYYY-MM')
    HISTORY_ID,
    CAR_ID,
    DATE_FORMAT(START_DATE, '%Y-%m-%d') START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') END_DATE,
    CASE WHEN
        DATEDIFF(END_DATE, START_DATE) +1 >= 30
    THEN '장기 대여'
    ELSE '단기 대여'
    END RENT_TYPE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE LIKE '2022-09-%'
ORDER BY
    HISTORY_ID DESC

-- TO_CHAR(SYSDATE, 'yyyymmdd')
-- TO_DATE(SYSDATE, 'YYYY-MM-DD')
-- case when then 활용
-- DATEDIFF('2024-12-25', '2024-12-16') -> 일차이
-- MYSQL 날짜변환 : DATE_FORMAT('~', '%Y-%m-%d')

-- ORACLE
SELECT
    HISTORY_ID,
    CAR_ID,
    TO_CHAR(START_DATE,'YYYY-MM-DD') START_DATE,
    TO_CHAR(END_DATE, 'YYYY-MM-DD') END_DATE,
    CASE WHEN
        END_DATE - START_DATE +1 >=30
    THEN '장기 대여'
    ELSE '단기 대여'
    END RENT_TYPE
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09'
ORDER BY
    HISTORY_ID DESC

 -- 오라클 DATEDIFF 없음!!!