-- LV1
-- SELECT
-- 조건에 부합하는 중고거래 댓글 조회하기

-- ORACLE
SELECT
    UB.TITLE,
    UB.BOARD_ID,
    UR.REPLY_ID,
    UR.WRITER_ID,
    UR.CONTENTS,
    TO_CHAR(UR.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM
    USED_GOODS_BOARD UB
JOIN
    USED_GOODS_REPLY UR
ON  UB.BOARD_ID = UR.BOARD_ID
WHERE
    TO_CHAR(UB.CREATED_DATE, 'YYYY-MM') IN ('2022-10')
ORDER BY
    CREATED_DATE ASC, TITLE ASC

-- MySQL
SELECT
    UGB.TITLE,
    UGB.BOARD_ID,
    UGR.REPLY_ID,
    UGR.WRITER_ID,
    UGR.CONTENTS,
    DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_BOARD UGB
JOIN
    USED_GOODS_REPLY UGR
ON
    UGB.BOARD_ID = UGR.BOARD_ID
WHERE
    SUBSTR(UGB.CREATED_DATE, 1, 7) = '2022-10'
ORDER BY
    UGR.CREATED_DATE, UGB.TITLE