-- 프로그래머스
-- SQL 고득점 Kit : SELECT
-- 12세 이하인 여자 환자 목록 출력하기

-- MySQL
-- CASE WHEN '조건' THEN '결과' ELSE '결과' END
-- IS NULL

SELECT
    PT_NAME,
    PT_NO,
    GEND_CD,
    AGE,
CASE WHEN TLNO IS NULL THEN 'NONE'
ELSE TLNO
END AS TLNO
FROM
    PATIENT
WHERE
    AGE <= 12
    AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME ASC