-- LV2
-- GROUP BY
-- 입양 시각 구하기(1)

-- Oracle
SELECT
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) "HOUR"
    , COUNT(DATETIME) "COUNT"
FROM
    ANIMAL_OUTS
WHERE
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 20
GROUP BY
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
ORDER BY
    1

-- Mysql
SELECT
    HOUR(DATETIME) AS HOUR,
    COUNT(DATETIME) AS COUNT
FROM
    ANIMAL_OUTS
GROUP BY
    HOUR
HAVING
    HOUR >= 9 AND HOUR <= 20
ORDER BY
    HOUR