-- LV2
-- GROUP BY
-- 성분으로 구분한 아이스크림 총 주문량

SELECT
    -- II.FLAVOR,
    II.INGREDIENT_TYPE,
    SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM
    ICECREAM_INFO II
JOIN
    FIRST_HALF FH
ON
    II.FLAVOR = FH.FLAVOR
GROUP BY
    II.INGREDIENT_TYPE
ORDER BY
    2;